spring:
  application:
    name: bank_rest
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
  profiles:
    active: h2
  server:
    port: ${SPRING_SERVER_PORT:8080}

springdoc:
  api-docs:
    enabled: true
    path: /api-docs

app:
  jwt:
    secret: ${JWT_SECRET}
    validity-seconds: ${JWT_VALIDITY:1800}
  encryption:
    secret: ${APP_ENCRYPTION_SECRET}
    salt: ${APP_ENCRYPTION_SALT}
  master-access:
    password: ${APP_MASTER_PASSWORD}